### ISSUE TITLE
command 'print-it.PrintIt' not found

### ISSUE THREAD

**Issue by mateeyow** [bmalehorn/vscode-print-it#5] opened 2020-12-22 09:50 UTC
I'm getting this error whenever I use it on any javascript file. Not sure how to debug or what is causing it. Using it on golang seems to work.
<img width="607" alt="image" src="https://user-images.githubusercontent.com/6420838/102875036-3aeb4f80-447e-11eb-9011-7083a4aa7631.png">

**Comment by bmalehorn** [comment] 2021-01-04 21:24
@mateeyow Not sure if this is caused by this extension - does it still happen if you quit & reopen vscode?

I've seen this error on all sorts of extensions, and it's usually fixed by restarting vscode.

**Comment by mateeyow** [comment] 2021-01-05 01:33
The error doesn't disappear even after I restart my VSCode nor my laptop. But when I use this plugin on another laptop it works.

**Comment by bmalehorn** [comment] 2021-01-05 19:50
@mateeyow Sounds like an issue with the installation - try uninstalling & reinstalling Print It and see what happens.

**Comment by mateeyow** [comment] 2021-03-24 07:31
Seems to be okay when I installed it on a new machine. On unrelated note, I can't seem to find your extension now.

**Closed as completed** 2022-04-29 21:48 UTC
